# -*- coding: utf-8 -*-
"""ead27maio_pratica1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JhMXnxONE3YYmVtrBmntFRvyoXdlUgPG
"""

# UNIT | Docente: Prof. MSc. Cloves Rocha
# EDA 27 de Maio - Pratica dos Algoritmos

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Dados de exemplo
x = [[5], [6], [7], [8], [9]]  # Variável independente
y = [6, 7, 8, 9, 5]  # Variável dependente

# Dividir os dados em conjunto de treinamento e conjunto de teste
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=80)

# Criar e treinar o modelo de regressão linear
model = LinearRegression()
model.fit(x_train, y_train)

# Fazer previsões no conjunto de teste
y_pred = model.predict(x_test)

# Avaliar o desempenho do modelo usando a métrica de erro médio quadrado (MSE)
mse = mean_squared_error(y_test, y_pred)
print('Erro médio quadrado (MSE):', mse)